used wrong index, needed to duplicate the key, ${region}-${type} for the transfer config (#183)
```
Error: Invalid index

  on .terraform/modules/event-recorder-cloudrun/modules/cloudevent-recorder/bigquery.tf line 146, in resource "google_monitoring_alert_policy" "bq_dts":
 146:         AND resource.labels.config_id = "${element(reverse(split("/", google_bigquery_data_transfer_config.import-job[conditions.key].name)), 0)}"
    ├────────────────
    │ conditions.key is "us-central1"
    │ google_bigquery_data_transfer_config.import-job is object with 6 attributes

The given key does not identify an element in this collection value.
```

Signed-off-by: Kenny Leung <kleung@chainguard.dev>