make additional webhook secrets optional (#666)
```
Error: Missing required argument

  on main.tf line 568, in module "github-events":
 568: module "github-events" {

The argument "additional_webhook_secrets" is required, but no definition was
found.
```

example;

https://github.com/chainguard-dev/mono/actions/runs/12317505331/job/34380184420?pr=21619

Signed-off-by: Kenny Leung <kleung@chainguard.dev>